#Python 2 with Image Processing Libraries
#
# --- Image Stack ---
# chiu0602/python2-imaging
# chiu0602/python2-baseline

FROM chiu0602/python2-baseline

RUN apt-get update && \
  apt-get install -y \
    libjpeg-turbo libjpeg-turbo-devel \
    libpng libpng-devel \
    libtiff libtiff-devel \
    freetype freetype-devel \
    openjpeg openjpeg-devel \
    zlib zlib-devel \
    libzip libzip-devel \
    lcms2 lcms2-devel \
    tcl tcl-devel \
    tk tk-devel \
    libwebp libwebp-devel \
    ImageMagick \