#Python 2 with Image Processing Libraries
#
# --- Image Stack ---
# chiu0602/python2-imaging
# chiu0602/python2-baseline

FROM chiu0602/python2-baseline

RUN apt-get update && \
  apt-get install -y \
    libgstreamer0.10-dev \
    libgl1-mesa-dev libglu1-mesa-dev \
    libgtk2.0-dev
